# Generated by Django 5.2.16 on 2026-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ground_crew', 'Ground Crew')], default='ground_crew', max_length=20),
        ),
    ]
