# Generated by Django 5.2.16 on 2026-08-07 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('airport_code', models.CharField(default='AMD', max_length=10)),
                ('status', models.CharField(default='available', max_length=20)),
                ('terminal', models.CharField(default='Terminal 1', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
