# Generated by Django 5.2.16 on 2026-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gate',
            name='current_flight_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='status',
            field=models.CharField(default='available', max_length=30),
        ),
    ]
