# Generated by Django 5.2.16 on 2026-08-07 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(default='fuel', max_length=50)),
                ('shift_start', models.DateTimeField(blank=True, null=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('assigned_flight_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='STANDBY', max_length=30)),
            ],
        ),
    ]
