# Generated by Django 5.2.16 on 2026-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='assigned_flight_id',
            new_name='assigned_flight',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
        migrations.AddField(
            model_name='staff',
            name='airport_code',
            field=models.CharField(default='AMD', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
