# Generated by Django 5.2.16 on 2026-08-07 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('callsign', models.CharField(max_length=50)),
                ('tail_number', models.CharField(max_length=50)),
                ('aircraft_type', models.CharField(default='A320neo', max_length=50)),
                ('airline', models.CharField(default='IndiGo', max_length=50)),
                ('airport_code', models.CharField(default='AMD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('callsign', models.CharField(max_length=50)),
                ('airline', models.CharField(default='IndiGo', max_length=50)),
                ('tail_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aircraft_type', models.CharField(default='A320neo', max_length=50)),
                ('route', models.CharField(default='AMD ✈️ DEL', max_length=100)),
                ('gate_id', models.CharField(blank=True, max_length=64, null=True)),
                ('aircraft_id', models.CharField(blank=True, max_length=64, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=30)),
                ('airport_code', models.CharField(default='AMD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
