# Generated by Django 5.2.16 on 2026-08-07 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSE',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='available', max_length=30)),
                ('assigned_flight', models.CharField(blank=True, max_length=64, null=True)),
                ('operator', models.CharField(default='Ramp Operations Crew', max_length=100)),
                ('fuel_level', models.IntegerField(default=85)),
                ('airport_code', models.CharField(default='AMD', max_length=10)),
            ],
        ),
    ]
