# Generated by Django 5.2.16 on 2026-08-07 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=64)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('assigned_staff_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
