# Generated by Django 5.2.16 on 2026-08-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('airport_code', models.CharField(default='AMD', max_length=10, primary_key=True, serialize=False)),
                ('temp_c', models.IntegerField(default=28)),
                ('condition', models.CharField(default='Clear', max_length=100)),
                ('severity', models.CharField(default='clear', max_length=20)),
                ('metar_raw', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
