# Generated by Django 5.2.16 on 2026-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='metar_raw',
        ),
        migrations.AddField(
            model_name='weather',
            name='visibility_km',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_kts',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='weather',
            name='airport_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
