# Generated by Django 5.2.16 on 2026-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='created_at',
            new_name='reported_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='airport_code',
            field=models.CharField(default='AMD', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
